# Generated by Django 5.0 on 2025-07-23 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=255)),
                ('profile_photo', models.ImageField(upload_to='photos/')),
                ('bio', models.TextField()),
                ('field_of_work', models.CharField(max_length=100)),
                ('impact_numbers', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='media/')),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominee_app.nominee')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('dossier', 'Dossier'), ('resume', 'Resume/Biodata'), ('recommendation', 'Letter of Recommendation'), ('news', 'News Article'), ('id', 'ID Proof')], max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominee_app.nominee')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominee_app.nominee')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=10)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominee_app.nominee')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='testimonials/')),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominee_app.nominee')),
            ],
        ),
    ]
