# Generated by Django 5.0 on 2025-07-25 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominee_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='award_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='certificate',
        ),
        migrations.AddField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 25, 12, 7, 36, 80332)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
