# Generated by Django 5.0 on 2025-07-29 07:22

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('nominee_app', '0002_rename_award_name_achievement_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementSubpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContributionSubpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSubpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MediaSubpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialSubpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),

        # 🔹 Optional field removal
        migrations.RemoveField(
            model_name='achievement',
            name='created_at',
        ),

        # 🔹 Field update
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(max_length=100),
        ),

        # ✅ Insert default subpoints
        migrations.RunSQL("INSERT INTO nominee_app_achievementsubpoint (id, title) VALUES (1, 'Default Achievement Subpoint');"),
        migrations.RunSQL("INSERT INTO nominee_app_contributionsubpoint (id, title) VALUES (1, 'Default Contribution Subpoint');"),
        migrations.RunSQL("INSERT INTO nominee_app_documentsubpoint (id, title) VALUES (1, 'Default Document Subpoint');"),
        migrations.RunSQL("INSERT INTO nominee_app_mediasubpoint (id, title) VALUES (1, 'Default Media Subpoint');"),
        migrations.RunSQL("INSERT INTO nominee_app_testimonialsubpoint (id, title) VALUES (1, 'Default Testimonial Subpoint');"),

        # 🔹 Add foreign keys with default=1
        migrations.AddField(
            model_name='achievement',
            name='subpoint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nominee_app.achievementsubpoint'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='subpoint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nominee_app.contributionsubpoint'),
        ),
        migrations.AddField(
            model_name='document',
            name='subpoint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nominee_app.documentsubpoint'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='subpoint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nominee_app.mediasubpoint'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='subpoint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nominee_app.testimonialsubpoint'),
        ),
    ]