# Generated by Django 5.0 on 2025-07-29 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominee_app', '0003_achievementsubpoint_contributionsubpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='subpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominee_app.contributionsubpoint'),
        ),
        migrations.AlterField(
            model_name='document',
            name='subpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominee_app.documentsubpoint'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='subpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominee_app.mediasubpoint'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='subpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominee_app.testimonialsubpoint'),
        ),
    ]
